### ISSUE TITLE
ModuleNotFoundError: No module named 'cobamp.utilities.context'

### ISSUE THREAD

**Issue by lokanandk** [BioSystemsUM/troppo#11]
Hi Skapur,

I'm new to using the Troppo pipeline. Also, I've never used Cobamp before. I wanted to reconstruct context-specific models using the troppo pipeline and installed the same using pip.
After installation of all dependencies, when I tried to run (just to check if the installation is ok):

$python imat.py

I get the following error:
Traceback (most recent call last):
  File "imat.py", line 8, in <module>
    from troppo.methods.base import ContextSpecificModelReconstructionAlgorithm, PropertiesReconstruction
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/__init__.py", line 1, in <module>
    from . import tINIT, corda, fastcore, gimme, imat, mba
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/methods/__init__.py", line 1, in <module>
    from . import tINIT, corda, fastcore, gimme, imat, mba
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/methods/gapfill/__init__.py", line 1, in <module>
    from . import tINIT, corda, fastcore, gimme, imat, mba
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/methods/gapfill/consensus.py", line 2, in <module>
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/tasks/__init__.py", line 1, in <module>
    from . import tINIT, corda, fastcore, gimme, imat, mba
  File "/home/kodurul/anaconda3/envs/carveme_me/lib/python3.6/site-packages/troppo-0.0.5-py3.6.egg/troppo/tasks/core.py", line 7, in <module>
ModuleNotFoundError: No module named 'cobamp.utilities.context'

Looks like the module "context" is missing? Please correct me if I'm wrong.

Could you please help me resolve this?

Thank you

Regards,
Loka

**Comment by skapur** [comment]
Hello Loka,

Thanks for pointing this issue! This is an issue on our side: troppo 0.0.5 depends on some new modules introduced in cobamp which are to be released on version 0.2, but this version isn't released yet. I will try to release the new version of cobamp which should fix the issue once you update it with pip. 

In the mean time, if you want to use troppo with the latest features, you can download the sources from GitHub (for both cobamp and troppo) and configure your editor accordingly to include the src folders in each project as source folders.

Once again, thank you for pointing this out as it also helps us keep these packages updated and working for everyone!
I will keep this issue updated.

**Comment by skapur** [comment]
I have released a new version of cobamp and tested the pip version of troppo on a fresh environment and everything should now be working once you run `pip install cobamp --upgrade`

I recommend that you check [this script](https://github.com/BioSystemsUM/troppo/blob/master/scripts/reconstruction_with_task_evaluation.py) for a real-world example using FASTCORE and tINIT, but feel free to ask if you run into any more issues

**Comment by lokanandk** [comment]
Thank you so much for your prompt response. I'll run the upgrade and get back to you if any more issues arise.
