### ISSUE TITLE
numpy problem in tINIT

### ISSUE THREAD

**Issue by aschluter** [BioSystemsUM/troppo#14]
Hi skapur,

I have a problem trying to run tINIT.  I get the following error from the tINIT-test.py file.

Thank you in advance,

Agatha

Traceback (most recent call last):
  File "tINIT_test.py", line 29, in <module>
    t.preprocessing()
  File "/home/agatha/.local/lib/python3.7/site-packages/troppo/methods/reconstruction/tINIT.py", line 114, in preprocessing
    self.reaction_scores = np.delete(self.reaction_scores, self.essential_reactions_idx)
  File "<__array_function__ internals>", line 6, in delete
  File "/home/agatha/.local/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4480, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by aschluter** [comment]
Hi skapur,

I solve it installing the dev version of troppo and cobamp.

thanks,
